### PR TITLE
allow navbar to be compiled and linked (like pages)

### PR DESCRIPTION
**Pull request by pierredavidbelanger**

### CODE REVIEW

**Comment by ashvin777** [comment]
Thanks @pierredavidbelanger , I will take a look at this PR.

**Comment by ashvin777** [comment]
Hi @pierredavidbelanger , not sure what is need of it. I think there is no specific event getting fired for navbar initialization. Is there any specific version of framework7 you are trying ? Can you explain me the exact problem statement.

**Comment by pierredavidbelanger** [comment]
@ashvin777 Yes, there is a specific event for this (http://v1.framework7.io/docs/plugins-api.html#available-hooks)

The "problem" is that when you [`$compile(pageData.container)`](https://github.com/ashvin777/framework7.angular/pull/21/files#diff-2fec33f9bd0ed0f57f52242b3153feffR38), you effectively only compile the `<div class="page">` portion of an html file, for example:

```html
<div class="navbar">
    <div class="navbar-inner">
        <div class="center sliding">{{propertyFromTheRootScope}}</div>
    </div>
</div>
<div class="pages">
    <div data-page="main" class="page" ng-controller="MyCtrl as ctrl">
        <div class="page-content">
            ...
        </div>
    </div>
</div>
```

What this PR is supposed to do, is to also  [`$compile(navbar.container)`](https://github.com/ashvin777/framework7.angular/pull/21/files#diff-2fec33f9bd0ed0f57f52242b3153feffR35) to compile the `<div class="navbar">` portion of this file for the interpolation magic to happens.

If you are unsure, just leave this PR unmerged. I will do more test in my realworld application and get back with comments or more push.

**Comment by ashvin777** [comment]
ok thanks for clarification. I am merging it in. :)

**Pull request merged**
